### ISSUE TITLE
–– [TASK] рефактор deadline policies

### ISSUE THREAD

**Issue by ronimizy** [itmo-is-dev/ASAP#120]
# Goal
Получить более логичную схему с дедлайнами

# Implementation
- Поменять DeadlinePolicy на DeadlinePenalty
- Добавить сущность DeadlinePolicy 
- Добавить в DeadlinePolicy логику расчёта penalty по Submission
- Добавить миграции

**Comment by Maksise4ka** [comment]
Судя по таске Эмина, мне не надо рефачить SubjectCourse и добавлять вместо HashSet<DeadlinePolicy> _deadlinePolicies новый DeadlinePolicy?
