### ISSUE TITLE
–– [TASK] Добавление identity ролей

### ISSUE THREAD

**Issue by ronimizy** [itmo-is-dev/ASAP#40]
## Parent
- #39 

# Goal
Добавление в систему ролей `Moderator`, `Mentor`

# Motivation
Для дальнейшей авторизации, мы должны различать, что пользователь является ментором в нашей системе

Так же, нужно поддержать возможность создания модераторов – администраторов системы, с ограниченными правами.

# Implementation
Должны быть созданы новые роли `Moderator` и `Mentor` в рамках Identity Framework

### Moderator
Данная роль, будет обозначать пользователей, которые могут выдавать другим пользователям менторский доступ.

### Mentor
Данная роль будет обозначать пользователей, которые могут иметь менторский доступ к сайту, она не влияет на менторский доступ к курсам предметов.

Для identity проекта нужно будет создать миграции, методы их вызывающие, вызвать их в настройки проекта.

**Comment by ronimizy** [comment]
Не особо хочется, чтобы остальной код напрямую взаимодействовал Identity Framework'ом. Поэтому нужно сделать абстракцию над текущим пользователем, его ролями и возможностями.
Стоит сделать это в виде комбинации Proxy+Special case. Т.е. будет интерфейс аля `ICurrentUser`, реализация для юзера, полученного через Identity Framework, и прокси, в котором бай дефолт лежит реализация `AnonymousUser`, а через какой-нибудь другой интерфейс, типа `ICurrentUserManager` можно будет заменить реализацию.

**Comment by xrem** [comment]
Так же нужно чтобы имеющиеся роуты эти роли как минимум начали использовать, а то толку от них мало
