### ISSUE TITLE
–– [TASK] Создание аккаунта пользователя (Backend)

### ISSUE THREAD

**Issue by ronimizy** [itmo-is-dev/ASAP#41]
## Parent
- #39 

## Blocked by
- #40 

# Goal
Поддержка системой создание аккаунта пользователя (identity), для существующего пользователя (domain) и изменения ролей.

# Motivation
На данный момент в системе присутствуют пользователи, занесённые как доменные пользователи вручную.
Нужно добавить возможность смапить их с identity пользователями, для доступа к системе.

# Implementation
- id создаваемого identity пользователя, должен совпадать с id доменного пользователя для которого создаётся аккаунт
- логин и пароль пользователя должен передаваться в запросе
- возможность создания пользователя должна быть только у администраторов и модераторов сервиса
- администраторам доступны любые роли для создания пользователя/обновления списка ролей
- модераторам доступна только роль ментора, для создания пользователя/обновления роли
- модератор не может обновлять роли администратора

**Comment by Zisrf** [comment]
"Смапить" значит только, что Id Identity и Domain пользователей совпадают?

**Comment by ronimizy** [comment]
> "Смапить" значит только, что Id Identity и Domain пользователей совпадают?

это значит, что нужна возможность на основе пользователя домена сделать пользователя identity. ну и да, айдишники должны совпадать.

**Comment by Zisrf** [comment]
И соответственно, если domain user является ментором, то и identity user получает эту роль?
