### ISSUE TITLE
–– [TASK] Получение информации преподавателем

### ISSUE THREAD

**Issue by ronimizy** [itmo-is-dev/ASAP#47]
## Parent
- #46 

## Blocked by
- #40 

# Goal
Добавить возможность пользователю с ролью `Mentor` получать предметы, на курсах которых он ментор, и курсы, на которых он ментор.

# Implementation
- Добавить роль `Mentor` в `Authorize` атрибуте к эндпоинту получения предметов и курсов по предмету
- Получение предметов, должно отдавать только те предметы, на которых пользователь ментор
- Получение курсов по предмету, должно отдавать только те курсы, где пользователь является ментором
- Получение курсов по предмету, должно выдавать ошибку, если пользователь не является ментором ни на одном из курсов
- Администратору и модератору доступны все данные

**Comment by Maksise4ka** [comment]
А может добавить в Authorize атрибут сразу роли ментора, админа и модератора? Типа
`[Authorize(Roles = $"{AsapIdentityRole.MentorRoleName}, {AsapIdentityRole.AdminRoleName}, {AsapIdentityRole.ModeratorRoleName}")]`

**Comment by ronimizy** [comment]
> А может добавить в Authorize атрибут сразу роли ментора, админа и модератора? Типа
> `[Authorize(Roles = $"{AsapIdentityRole.MentorRoleName}, {AsapIdentityRole.AdminRoleName}, {AsapIdentityRole.ModeratorRoleName}")]`

ты немного проиграл в синтаксис, но да, идея валидная. (но она не отменяет авторизации на слое приложения)
