### ISSUE TITLE
–– [TASK] Создание аккаунта пользователя (Testing)

### ISSUE THREAD

**Issue by ronimizy** [itmo-is-dev/ASAP#74]
## Parent
- #39 

```[tasklist]
## Blocked by
- [ ] #41 
```

# Goal
Полное покрытие тестами добавленного кода

# Implementation
Сделать тесты для добавленных хендлеров на каждый из типов текущих юзеров. Для типов UserManager/RoleManager использовать моки через [Moq](https://www.nuget.org/packages/Moq). Для IDatabaseContext использовать свойство базового класса.

**Comment by Zisrf** [comment]
Может быть просто использовать sqlite для IdentityDbContext'а? Успешно замокать у меня пока особо не получилось

**Comment by Zisrf** [comment]
И ещё, почему бы не использовать Xunit.DependencyInjection?
